name: Basico
version: '${version}'

main: org.jslealm.basico.Basico
api-version: '26.2'

authors: [JsLealM]

commands:
  mtools:
    description: Comando Herramientas Mondaland
    usage: /mtools <argumento>
    aliases:
      - mt
  monda:
    description: "Comando de Mondaland"
    usage: /monda <argumento>
    aliases:
      - mnd
      - pn
  metodo:
    description: "Comando de Mondaland Metodo"
    usage: /metodo <argumento>
    aliases:
      - met
      - mtd
  anonimo:
    description: "Comadno anonimo"
    usage: /anonimo <argumento>
  ejercicio:
    description: "Comando Ejercicio Practicar Logica y Spigot"
    usage: /ejercicio <argumento>
    aliases:
      - ej
permissions:
  ejercicio.admin:
    description: Este es el permiso para admin
    default: op
  mtools.admin:
    description: Permiso admin para mtools
    default: op