name: Basico
version: '1.0-SNAPSHOT'

main: org.jslealm.basico.Basico
api-version: '26.2'

authors: [JsLealM]

commands:
  monda:
    description: "Comando de Mondaland"
    usage: /monda <argumento>
    aliases:
      - mnd
      - pn
  metodo:
    description: "Comando de Mondaland Metodo"
    usage: /metodo <argumento>
    aliases:
      - met
      - mtd
  anonimo:
    description: "Comadno anonimo"
    usage: /anonimo <argumento>